/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fakeifood;

import db.BuscaDados;
import db.InsereDados;
import java.math.BigDecimal;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author arnor
 */
public class FrameCarrinho extends javax.swing.JDialog {

    private DefaultListModel model;
    private BigDecimal valorFrete;
    private BigDecimal valorTotal;
    private BigDecimal valorParcial;

    /**
     * Creates new form FrameCarrinho
     */
    public FrameCarrinho() {
        initComponents();
        valorFrete = new BigDecimal("" + 0);
        valorTotal = new BigDecimal("" + 0);
        valorParcial = new BigDecimal("" + 0);
        setModal(true);

        BuscaDados buscar = new BuscaDados();

        ResultSet rsEnd;
        try {
            rsEnd = buscar.selectClienteEndereco(FramePrincipalCliente.getId_cliente());

            while (rsEnd.next()) {
                boxEndereco.addItem(rsEnd.getString("endereco"));
            }

            rsEnd.close();

        } catch (SQLException ex) {
            Logger.getLogger(FrameCarrinho.class.getName()).log(Level.SEVERE, null, ex);
        }

        Carrinho c = FramePrincipalCliente.getCarrinho();

        DefaultListModel model = new DefaultListModel();
        for (int i = 0; i < c.id_pratos.size(); i++) {
            BigDecimal precoItem = new BigDecimal("" + c.preco_pratos.get(i));
            BigDecimal quantidade = new BigDecimal("" + c.quantidades.get(i));
            precoItem = precoItem.multiply(quantidade);
            
            valorParcial = valorParcial.add(precoItem);
            model.addElement(c.nome_pratos.get(i) + " - " + c.quantidades.get(i) + " und. - " + "R$ " + precoItem);
        }
        listCarrinho.setModel(model);

        lblValorParcial.setText("R$ " + valorParcial);

        try {

            if (buscar.selectRestauranteEntrega(c.getRestaurante())) {
                //é entrega rápida
                valorFrete = valorFrete.add(new BigDecimal("" + 2));
                lblValorFrete.setText("R$ " + valorFrete);
            } else {
                lblValorFrete.setText("Grátis");

            }

        } catch (SQLException ex) {
            Logger.getLogger(FrameCarrinho.class.getName()).log(Level.SEVERE, null, ex);
        }

        valorTotal = valorTotal.add(valorParcial);
        valorTotal = valorTotal.add(valorFrete);
        lblValorTotal.setText("R$ " + valorTotal);

        this.model = model;

        repaint();
        revalidate();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listCarrinho = new javax.swing.JList<>();
        btnRemoveItem = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lblValorTotal = new javax.swing.JLabel();
        btnFinalizar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblValorFrete = new javax.swing.JLabel();
        lblValorParcial = new javax.swing.JLabel();
        boxEndereco = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();

        jButton3.setText("jButton3");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Carrinho");

        jScrollPane1.setViewportView(listCarrinho);

        btnRemoveItem.setBackground(new java.awt.Color(255, 204, 153));
        btnRemoveItem.setText("Remover Item");
        btnRemoveItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveItemActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Valor Total:");

        lblValorTotal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblValorTotal.setText("0");

        btnFinalizar.setBackground(new java.awt.Color(255, 204, 153));
        btnFinalizar.setText("Finalizar Pedido");
        btnFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Valor:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Frete:");

        lblValorFrete.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblValorFrete.setText("0");

        lblValorParcial.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblValorParcial.setText("0");

        jLabel5.setText("Endereço de Entrega:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(btnRemoveItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblValorTotal)
                                    .addComponent(jLabel2))
                                .addGap(49, 49, 49))
                            .addComponent(btnFinalizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(lblValorParcial))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(lblValorFrete)))
                            .addComponent(boxEndereco, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jLabel5))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jLabel1)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRemoveItem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addGap(2, 2, 2)
                .addComponent(boxEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblValorParcial)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblValorFrete))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblValorTotal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnFinalizar)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRemoveItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveItemActionPerformed
        // TODO add your handling code here:

        Carrinho c = FramePrincipalCliente.getCarrinho();

        if (listCarrinho.getSelectedValue() == null) {
            //Não faz nada
        } else {
            int index = listCarrinho.getSelectedIndex();
            BigDecimal precoItem = new BigDecimal("" + c.preco_pratos.get(index));
            BigDecimal quantidade = new BigDecimal("" + c.quantidades.get(index));
            precoItem = precoItem.multiply(quantidade);
            
            // p isso funcionar, teria que colocar valorParcial e valorTotal como bigdecimal, e na hora d emnadar p o carrinho
            // mesmo acho que funcionaria por o (""+ tal) pq ele printa direitinho no sout

            valorParcial = valorParcial.subtract(precoItem);
            valorTotal = valorTotal.subtract(precoItem);
            
            model.remove(index);
            FramePrincipalCliente.getCarrinho().removeItem(index);

            lblValorParcial.setText("R$ " + valorParcial);
            lblValorTotal.setText("R$ " + valorTotal);

            listCarrinho.repaint();
            listCarrinho.revalidate();
        }
    }//GEN-LAST:event_btnRemoveItemActionPerformed

    private void btnFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarActionPerformed
        try {

            // TODO add your handling code here:
            if (listCarrinho.getLastVisibleIndex() == -1) {
                this.setVisible(false);
                JOptionPane.showMessageDialog(null, "Você precisa ter pelo menos um item no \n carrinho para finalizar um pedido");
                this.setVisible(true);
            } else {

                Carrinho c = FramePrincipalCliente.getCarrinho();

                BuscaDados buscar = new BuscaDados();
                InsereDados inserir = new InsereDados();
                
                inserir.inserePedido(FramePrincipalCliente.getId_cliente(), c.getRestaurante(),
                        buscar.selectDate(), buscar.selectTime(), (String) boxEndereco.getSelectedItem(), "" + valorTotal, "" + valorFrete);
                
                int i = 0;
                for (int quantidade : c.quantidades) {
                    inserir.insereCarrinho(buscar.selectLastIdPedido(), c.id_pratos.get(i), quantidade);
                    i++;
                }
                
                c.esvaziaCarrinho();
                
                this.setVisible(false);
                JOptionPane.showMessageDialog(null, "Pedido feito com sucesso. :D");
                this.dispose(); 
            }

        } catch (SQLException ex) {
            Logger.getLogger(FrameCarrinho.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnFinalizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameCarrinho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameCarrinho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameCarrinho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameCarrinho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new FrameCarrinho().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxEndereco;
    private javax.swing.JButton btnFinalizar;
    private javax.swing.JButton btnRemoveItem;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblValorFrete;
    private javax.swing.JLabel lblValorParcial;
    private javax.swing.JLabel lblValorTotal;
    private javax.swing.JList<String> listCarrinho;
    // End of variables declaration//GEN-END:variables
}
