/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fakeifood;

import db.AtualizaDados;
import db.BuscaDados;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author danda
 */
public class FramePrincipalRestaurante extends javax.swing.JFrame implements ActionListener {

    public static int id_restaurante;

    public FramePrincipalRestaurante(int id_restaurante) throws SQLException {
        initComponents();
        this.id_restaurante = id_restaurante;
        BuscaDados BD = new BuscaDados();
        ResultSet restaurante = BD.selectRestauranteSelecionado(id_restaurante);
        
        if(restaurante.getInt("aberto") == 1){
            lblStatusRestaurante.setText("Status do restaurante: Aberto");
            btnStatusRestaurante.setText("Clique para fechar o restaurante");
        }else{
            lblStatusRestaurante.setText("Status do restaurante: Fechado");
            btnStatusRestaurante.setText("Clique para abrir o restaurante");
        }
        if(restaurante.getInt("entrega_rapida") == 1){
            lblTipoEntrega.setText("Tipo de entrega: Rápida");
        }else{
            lblTipoEntrega.setText("Tipo de entrega: Grátis");
        }
        restaurante.close();
        arrumar();

    }

    public void arrumar() throws SQLException {
        BuscaDados buscar = new BuscaDados();
        ResultSet rs = buscar.selectRestaurantePratos(id_restaurante);
        // preenche gridlayout
        while (rs.next()) {
            ResultSet precoAtual = buscar.selectPratoPrecos(rs.getInt("id_prato"));
            pnlEditarPrato EP = new pnlEditarPrato(rs.getString("nome_prato"), precoAtual.getString("valor_preco"), rs.getString("descricao"), rs.getInt("id_prato"));
            // coloca listener no botão p que quando a pessoa clique em adicionar, atualize o grid
            EP.getBotao().addActionListener(this);

            precoAtual.close();
            pnlPratos.add(EP);
        }

        rs.close();
        repaint();
        revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pnlPratos = new javax.swing.JPanel();
        btnAdicionarPrato = new javax.swing.JButton();
        btnPedidosDia = new javax.swing.JButton();
        btnPrecoMedio = new javax.swing.JButton();
        btnPedidosSemana = new javax.swing.JButton();
        btnPedidosMes = new javax.swing.JButton();
        btnMaisPedido = new javax.swing.JButton();
        btnStatusRestaurante = new javax.swing.JButton();
        lblStatusRestaurante = new javax.swing.JLabel();
        lblTipoEntrega = new javax.swing.JLabel();
        btnTipoEntrega = new javax.swing.JButton();
        btnCategorias = new javax.swing.JButton();
        btnConfiguracao = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        txtLogoMarca = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        pnlPratos.setBackground(new java.awt.Color(255, 255, 255));
        pnlPratos.setLayout(new java.awt.GridLayout(0, 2, 8, 8));
        jScrollPane1.setViewportView(pnlPratos);

        btnAdicionarPrato.setBackground(new java.awt.Color(255, 204, 153));
        btnAdicionarPrato.setText("Adicionar novo prato ao menu");
        btnAdicionarPrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarPratoActionPerformed(evt);
            }
        });

        btnPedidosDia.setBackground(new java.awt.Color(255, 204, 153));
        btnPedidosDia.setText("Relatório de pedidos do dia");
        btnPedidosDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPedidosDiaActionPerformed(evt);
            }
        });

        btnPrecoMedio.setBackground(new java.awt.Color(255, 204, 153));
        btnPrecoMedio.setText("Preço médio de pratos (7 dias)");
        btnPrecoMedio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrecoMedioActionPerformed(evt);
            }
        });

        btnPedidosSemana.setBackground(new java.awt.Color(255, 204, 153));
        btnPedidosSemana.setText("Relatório de pedidos da semana");
        btnPedidosSemana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPedidosSemanaActionPerformed(evt);
            }
        });

        btnPedidosMes.setBackground(new java.awt.Color(255, 204, 153));
        btnPedidosMes.setText("Relatório de pedidos do mês");
        btnPedidosMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPedidosMesActionPerformed(evt);
            }
        });

        btnMaisPedido.setBackground(new java.awt.Color(255, 204, 153));
        btnMaisPedido.setText("Prato mais pedido a cada mês");
        btnMaisPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMaisPedidoActionPerformed(evt);
            }
        });

        btnStatusRestaurante.setBackground(new java.awt.Color(255, 204, 153));
        btnStatusRestaurante.setText("Clique para abrir restaurante");
        btnStatusRestaurante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStatusRestauranteActionPerformed(evt);
            }
        });

        lblStatusRestaurante.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblStatusRestaurante.setText("Status do Restaurante: aberto");

        lblTipoEntrega.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTipoEntrega.setText("Tipo de entrega: rápida");

        btnTipoEntrega.setBackground(new java.awt.Color(255, 204, 153));
        btnTipoEntrega.setText("Clique para mudar tipo de entrega");
        btnTipoEntrega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTipoEntregaActionPerformed(evt);
            }
        });

        btnCategorias.setBackground(new java.awt.Color(255, 204, 153));
        btnCategorias.setText("Gerenciar categorias do restaurante");
        btnCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCategoriasActionPerformed(evt);
            }
        });

        btnConfiguracao.setBackground(new java.awt.Color(255, 204, 153));
        btnConfiguracao.setText("Configurações");
        btnConfiguracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfiguracaoActionPerformed(evt);
            }
        });

        btnSair.setBackground(new java.awt.Color(255, 204, 153));
        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        txtLogoMarca.setBackground(new java.awt.Color(255, 153, 102));
        txtLogoMarca.setFont(new java.awt.Font("Square721 Cn BT", 0, 36)); // NOI18N
        txtLogoMarca.setForeground(new java.awt.Color(255, 153, 102));
        txtLogoMarca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/foodeliveryPequeno.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Altere as categorias do seu restaurante!");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Relatórios do Restaurante");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Dados temporais");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 963, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtLogoMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(589, 589, 589)
                .addComponent(btnConfiguracao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnSair)
                .addGap(67, 67, 67))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel2)
                            .addComponent(btnCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(btnPedidosDia, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPedidosSemana, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPedidosMes, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(61, 61, 61)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(lblTipoEntrega)
                            .addComponent(btnTipoEntrega)
                            .addComponent(jLabel1)
                            .addComponent(btnPrecoMedio, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMaisPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(59, 59, 59)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(lblStatusRestaurante)
                            .addComponent(btnStatusRestaurante, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(85, 85, 85))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnAdicionarPrato, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(txtLogoMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSair)
                            .addComponent(btnConfiguracao))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTipoEntrega)
                            .addComponent(lblStatusRestaurante, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnStatusRestaurante)
                                .addComponent(btnCategorias))
                            .addComponent(btnTipoEntrega)))
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPedidosDia)
                    .addComponent(btnPrecoMedio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPedidosSemana)
                    .addComponent(btnMaisPedido))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPedidosMes)
                .addGap(33, 33, 33)
                .addComponent(btnAdicionarPrato)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 965, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        // TODO add your handling code here:
        dispose();
        FrameInicial FI = new FrameInicial();
        FI.setVisible(true);
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnConfiguracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfiguracaoActionPerformed
        // TODO add your handling code here:
        FrameConfiguracaoRestaurante CR = new FrameConfiguracaoRestaurante();
        CR.setVisible(true);
    }//GEN-LAST:event_btnConfiguracaoActionPerformed

    private void btnCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCategoriasActionPerformed
        try {
            // TODO add your handling code here:
            FrameGerenciarCategorias GC = new FrameGerenciarCategorias();
            GC.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(FramePrincipalRestaurante.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnCategoriasActionPerformed

    private void btnTipoEntregaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTipoEntregaActionPerformed
        // TODO add your handling code here:
        AtualizaDados AD = new AtualizaDados();
        String status = lblTipoEntrega.getText();
        int index = status.indexOf(":") + 2;
        status = status.substring(index);
        if(status.equals("Rápida")){
            AD.atualizaEntrega(FramePrincipalRestaurante.id_restaurante, 0);
            lblTipoEntrega.setText("Tipo de entrega: Grátis");
        }else{
            AD.atualizaEntrega(FramePrincipalRestaurante.id_restaurante, 1);
            lblTipoEntrega.setText("Tipo de entrega: Rápida");
        }
    }//GEN-LAST:event_btnTipoEntregaActionPerformed

    private void btnStatusRestauranteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStatusRestauranteActionPerformed
        // TODO add your handling code here:
        AtualizaDados AD = new AtualizaDados();
        String status = lblStatusRestaurante.getText();
        int index = status.indexOf(":") + 2;
        status = status.substring(index);
        if(status.equals("Aberto")){
            AD.atualizaStatus(FramePrincipalRestaurante.id_restaurante, 0);
            lblStatusRestaurante.setText("Status do restaurante: Fechado");
            btnStatusRestaurante.setText("Clique para abrir o restaurante");
        }else{
            AD.atualizaStatus(FramePrincipalRestaurante.id_restaurante, 1);
            lblStatusRestaurante.setText("Status do restaurante: Aberto");
            btnStatusRestaurante.setText("Clique para fechar o restaurante");
        }
    }//GEN-LAST:event_btnStatusRestauranteActionPerformed

    private void btnMaisPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMaisPedidoActionPerformed
        try {
            // TODO add your handling code here:
            BuscaDados BD = new BuscaDados();
            ResultSet rs = BD.selectPratoMaisVendidoMes(FramePrincipalRestaurante.id_restaurante);
            if(rs.isClosed()){
                JOptionPane.showMessageDialog(this, "Ainda não houveram pedidos esse mês.");
            }else{
                String nome = rs.getString("nome_prato");
                String quantidade = "" + rs.getInt("SUM(quantidade)");
                rs.close();
                JOptionPane.showMessageDialog(this, "O prato mais vendido desse mês até agora: " + nome + "\n A quantidade vendida foi: " + quantidade + "unds.", "Informação sobre prato mais vendido", JOptionPane.PLAIN_MESSAGE);
            }
        } catch (SQLException ex) {
            Logger.getLogger(FramePrincipalRestaurante.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnMaisPedidoActionPerformed

    private void btnPedidosMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPedidosMesActionPerformed
        // TODO add your handling code here:
        FrameRelatorioPedidos RP = new FrameRelatorioPedidos(false, false, true);
        RP.setVisible(true);
    }//GEN-LAST:event_btnPedidosMesActionPerformed

    private void btnPedidosSemanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPedidosSemanaActionPerformed
        // TODO add your handling code here:
        FrameRelatorioPedidos RP = new FrameRelatorioPedidos(false, true, false);
        RP.setVisible(true);
    }//GEN-LAST:event_btnPedidosSemanaActionPerformed

    private void btnPrecoMedioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrecoMedioActionPerformed
        try {
            // TODO add your handling code here:
            FrameRelatorioPrecoMedio RPM = new FrameRelatorioPrecoMedio();
            RPM.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(FramePrincipalRestaurante.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnPrecoMedioActionPerformed

    private void btnPedidosDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPedidosDiaActionPerformed
        // TODO add your handling code here:
        FrameRelatorioPedidos RP = new FrameRelatorioPedidos(true, false, false);
        RP.setVisible(true);
    }//GEN-LAST:event_btnPedidosDiaActionPerformed

    private void btnAdicionarPratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarPratoActionPerformed
        // TODO add your handling code here:
        FrameAdicionarPrato AP = new FrameAdicionarPrato();
        // loop que preenche grid só e espera a pessoa clicar no botão de adicionar o prato
        AP.addWindowListener(new WindowAdapter() {
            public void windowClosed(WindowEvent e) {
                try {
                    pnlPratos.removeAll();
                    arrumar();
                } catch (SQLException ex) {
                    Logger.getLogger(pnlEditarPrato.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });

        AP.setVisible(true);
    }//GEN-LAST:event_btnAdicionarPratoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FramePrincipalRestaurante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FramePrincipalRestaurante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FramePrincipalRestaurante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FramePrincipalRestaurante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new FramePrincipalRestaurante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionarPrato;
    private javax.swing.JButton btnCategorias;
    private javax.swing.JButton btnConfiguracao;
    private javax.swing.JButton btnMaisPedido;
    private javax.swing.JButton btnPedidosDia;
    private javax.swing.JButton btnPedidosMes;
    private javax.swing.JButton btnPedidosSemana;
    private javax.swing.JButton btnPrecoMedio;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnStatusRestaurante;
    private javax.swing.JButton btnTipoEntrega;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblStatusRestaurante;
    private javax.swing.JLabel lblTipoEntrega;
    private javax.swing.JPanel pnlPratos;
    private javax.swing.JLabel txtLogoMarca;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent ae) {
        try {
            pnlPratos.removeAll();
            arrumar();
        } catch (SQLException ex) {
            Logger.getLogger(FramePrincipalRestaurante.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
