/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fakeifood;

import db.BuscaDados;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 *
 * @author arnor
 */
public class FrameMenuRestaurante extends javax.swing.JFrame {

    /**
     * Creates new form FrameMenuRestaurante
     */
    public FrameMenuRestaurante(int id_restaurante) throws SQLException {
        initComponents();

        BuscaDados buscar = new BuscaDados();
        ResultSet rs = buscar.selectRestaurantePratos(id_restaurante);

        while (rs.next()) {
            ResultSet precoAtual = buscar.selectPratoPrecos(rs.getInt("id_prato"));
            precoAtual.getString("valor_preco");
            rs.getString("descricao");
            pnlPreviewPrato PP = new pnlPreviewPrato(rs.getString("nome_prato"), precoAtual.getString("valor_preco"), rs.getString("descricao"), rs.getInt("id_prato"), rs.getInt("id_restaurante"));
            precoAtual.close();
            pnlPratos.add(PP);
        }
        
        rs.close();

        ResultSet restaurante = buscar.selectRestauranteSelecionado(id_restaurante);

        String status;
        if (restaurante.getBoolean("aberto")) {
            status = "aberto";
        } else {
            status = "fechado";
        }
        
        ResultSet categorias = buscar.selectRestauranteCategorias(id_restaurante);
        String categoriasString = "| ";
        while(categorias.next()){
            categoriasString += (categorias.getString("nome_categoria") + " | ");
        }
        
        fldDescricao.setText("Categorias: " + categoriasString + "\n"
                           + "Endereço: " + restaurante.getString("endereco_restaurante") + "\n");
        
        lblNomeRestaurante.setText(restaurante.getString("nome_restaurante"));
        if(restaurante.getInt("aberto") == 1){
            lblAberto.setText("O restaurante está aberto!");
        }else{
            lblAberto.setText("O restaurante está fechado.");
        }
        
        if(restaurante.getBoolean("entrega_rapida")){
            lblEntrega.setText("O tipo de entrega é: Entrega rápida");
        }else
            lblEntrega.setText("O tipo de entrega é: Entrega grátis");
        
        restaurante.close();
        categorias.close();

        repaint();
        revalidate();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlRestaurante = new javax.swing.JPanel();
        lblNomeRestaurante = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pnlPratos = new javax.swing.JPanel();
        lblpratos = new javax.swing.JLabel();
        lblEntrega = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        fldDescricao = new javax.swing.JTextArea();
        lblAberto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnlRestaurante.setBackground(new java.awt.Color(255, 255, 255));

        lblNomeRestaurante.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblNomeRestaurante.setForeground(new java.awt.Color(255, 153, 102));
        lblNomeRestaurante.setText("Nome");

        pnlPratos.setBackground(new java.awt.Color(255, 255, 255));
        pnlPratos.setLayout(new java.awt.GridLayout(0, 2, 8, 8));
        jScrollPane1.setViewportView(pnlPratos);

        lblpratos.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblpratos.setForeground(new java.awt.Color(255, 153, 102));
        lblpratos.setText("Pratos");

        lblEntrega.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblEntrega.setForeground(new java.awt.Color(255, 153, 102));
        lblEntrega.setText("Tipo de entrega");

        fldDescricao.setEditable(false);
        fldDescricao.setColumns(20);
        fldDescricao.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        fldDescricao.setForeground(new java.awt.Color(255, 153, 102));
        fldDescricao.setRows(5);
        fldDescricao.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 153)));
        fldDescricao.setCaretColor(new java.awt.Color(255, 204, 153));
        jScrollPane2.setViewportView(fldDescricao);

        lblAberto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblAberto.setForeground(new java.awt.Color(255, 153, 102));
        lblAberto.setText("O restaurante está ");

        javax.swing.GroupLayout pnlRestauranteLayout = new javax.swing.GroupLayout(pnlRestaurante);
        pnlRestaurante.setLayout(pnlRestauranteLayout);
        pnlRestauranteLayout.setHorizontalGroup(
            pnlRestauranteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(pnlRestauranteLayout.createSequentialGroup()
                .addGroup(pnlRestauranteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlRestauranteLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblpratos))
                    .addGroup(pnlRestauranteLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(pnlRestauranteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblNomeRestaurante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlRestauranteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEntrega)
                            .addComponent(lblAberto))))
                .addContainerGap(455, Short.MAX_VALUE))
        );
        pnlRestauranteLayout.setVerticalGroup(
            pnlRestauranteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRestauranteLayout.createSequentialGroup()
                .addGroup(pnlRestauranteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlRestauranteLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(lblNomeRestaurante, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                        .addGap(72, 72, 72))
                    .addGroup(pnlRestauranteLayout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(lblEntrega)
                        .addGap(87, 87, 87)
                        .addComponent(lblAberto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(lblpratos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlRestaurante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlRestaurante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameMenuRestaurante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameMenuRestaurante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameMenuRestaurante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameMenuRestaurante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new FrameMenuRestaurante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea fldDescricao;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAberto;
    private javax.swing.JLabel lblEntrega;
    private javax.swing.JLabel lblNomeRestaurante;
    private javax.swing.JLabel lblpratos;
    private javax.swing.JPanel pnlPratos;
    private javax.swing.JPanel pnlRestaurante;
    // End of variables declaration//GEN-END:variables
}
